spring:
  application:
    name: execution-service
  cassandra:
    keyspace-name: kairos
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    schema-action: create_if_not_exists

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: execution-service
      auto-offset-reset: earliest
      enable-auto-commit: false

kairos:
  kafka:
    topic:
      task-execution: task-execution

server:
  port: 8993